service:
    name: image-service               # service name
    max_workers: 10                   # multithread
    max_retries: 5                    # Number of retry attempts after failure
    connect_timeout_sec: 15           # Wait the port to be listend
    render_timeout_sec: 25            # max gradio rendering time 
    process_timeout_sec: 200          # Processing timeout for long-running tasks
    storage:
        type: minio      # minio / local
        local:
            base_dir:  screenshots/
   
openai:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen3-coder-flash

log:
    base_dir: log/
    file_name: service.log
    roll_max_bytes: 524288000  # 500MB   
    backup_count: 180
    format: '%(asctime)s - %(name)s - %(processName)s - %(threadName)s - %(filename)s[line:%(lineno)d] - %(levelname)s - %(message)s'