papergen:
  host: 0.0.0.0
  http_port: 8686

openai:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen3-coder-30b-a3b-instruct

mongodb:
    uri: mongodb://admin:123456@mongodb:27017/
    db_name: papergen
    collection_name: request_progress

selenium:
    url: http://selenium:4444/wd/hub
