openai:
    base_url: http://localhost:8000/v1
    api_key: sk-XXXXXX
    model: Qwen2.5-Coder-3B-Instruct

selenium:
    url: http://localhost:4444/wd/hub
    
mongodb:
    uri: mongodb://website_online:hZc8f7zEqX@mongo2.aimc.offline:27017,mongo3.aimc.offline:27018,mongo4.aimc.offline:27019/?replicaSet=mongos
    db_name: website_generation
    collection_name: website_info_online
