class InvalidJSONError(Exception):
    # input JSON validation
    pass

class OpenAIError(Exception):
    # errors related to OpenAI
    pass

class ChromeError(Exception):
    # errors related to chrome selenium
    pass

class FileSystemError(Exception):
    # errors related to DFS
    pass

class FrontendError(Exception):
    # frontend render/compile error
    pass

class MaxRetriesExceededError(Exception):
    # max retries of one task
    pass

class RenderTimeoutError(Exception):
    # time limit for gradio rendering
    pass

class PortTimeoutError(Exception):
    # waiting port times out
    pass

class FormatError(Exception):
    # invalid code (.jsx) format generated by LLM
    pass

