class FrontendError(Exception):
    # frontend render/compile error
    pass

class UploadError(Exception):
    # error when upload files
    pass

class MaxRetriesExceededError(Exception):
    # max retries of one task
    pass

class RenderTimeoutError(Exception):
    # time limit for gradio rendering
    pass


class FormatError(Exception):
    # invalid code (.jsx) format generated by LLM
    pass